# Generated by Django 4.0.5 on 2022-06-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='* 캐릭터, 배경과 관련된 NFT만 게시!', max_length=200, verbose_name='게시글 제목')),
                ('author', models.CharField(max_length=100, verbose_name='작성자')),
                ('content', models.TextField(max_length=200, verbose_name='내용')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='업데이트일')),
            ],
            options={
                'db_table': 'sales_board',
            },
        ),
    ]
